---
- hosts: all
  become: true

  tasks:
    - name: remove docker images
      shell: docker image rm -f sohamjoshi/formula-one-bot:latest
    - name: Pull sohamjoshi/formula-one-bot
      shell: docker pull sohamjoshi/formula-one-bot
